import hashlib
m = hashlib.shake_256(b"mon message")
m.update(b"qsdfkdfjkqlsndfklSEIROUTYHNX?SQNCIOZ")
# print(m.digest(42))
# print(m.hexdigest(42))
dk = hashlib.pbkdf2_hmac('sha256', b'password', b'salt', 100000)
print(dk)
print(m)
# print(hashlib.algorithms_guaranteed)
# print(hashlib.algorithms_available)